### ISSUE TITLE
Unable to install in fresh Xamarin project

### ISSUE THREAD

**Issue by Rambalac** [1iveowl/SocketLite#2]
Reproducing

* Create new Xamarin Xaml project
* Add SocketLite.PCL to Portable project- > fail

* Open Portable project preferences
* Open Targets -> Change
* Remove Phone 8.1 and .NET Core
* Set .NET Framework to 4.5.1
* Add  SocketLite.PCL to Portable project- > fail

The only working version is 2.0.20

Your Nuget Project Site is showing Error 404.

**Comment by 1iveowl** [comment]
Thank you.

You are having these issues because your project requires profile 111. This only works for version 2.20.0 as stated at the project site.

I've fixed the Nuget Project site. Nuget 2.20.0 was pointing to nowhere. Later NuGet versions are ok.
