### ISSUE TITLE
5.0.0 package net46 incorrect version number

### ISSUE THREAD

**Issue by BlythMeister** [1iveowl/SocketLite#23]
Within the version 5.0.0 nuget package, the net46 version appears to have the version number 4.2 rather than 5.0.0.

This is causing me errors when taking your library as a 2nd level dependency which is expecting a 5.0.0

**Comment by 1iveowl** [comment]
Thank you for catching this. 

I'm away on vacation the next week's, but feel free to do a PR and I might be able to process it remotely.

**Comment by BlythMeister** [comment]
I'm also on vacation for 2 weeks 😂
Plus I'm not sure what the update needs to be and where as I can't find a match for the version number in the DLL in the codebase.

**Comment by 1iveowl** [comment]
OK. Will look at it when back then 😉

**Comment by BlythMeister** [comment]
Perfect thanks!
Enjoy your vacation 🙂

**Comment by BlythMeister** [comment]
@1iveowl just had a look at the versions and think everything is ok in the codebase, though this doesn't match the contents of the package...so maybe it just needs a rebuild and publish to fix?

**Comment by BlythMeister** [comment]
To clarify the issue, it's the PCL lib which is the wrong version.

**Comment by 1iveowl** [comment]
There was an issue with the build script. It have been fixed with version 5.0.1.
