### ISSUE TITLE
Assemblies error on iOS on Xamarin.Forms

### ISSUE THREAD

**Issue by JFDionne** [1iveowl/SocketLite#28]
Hi, as soon I install the package and try to use it, when I build I got this error:

error MT2001: Could not link assemblies. Reason: Error while processing references of 'App.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by 1iveowl** [comment]
Sry. Not much to go on here. I haven't seen this before. Any more details you can share?

**Comment by JFDionne** [comment]
Hi, yes, I have those warning too, I didn't see them before:

     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(793,3): warning MT0129: Debugging symbol file for '/Users/jfdionne/Library/Caches/Xamarin/mtbs/builds/App5.iOS/e7b3b86f111a793b6ccb2bd736c11944/bin/iPhone/Debug/ISocketLite.PCL.dll' does not match the assembly and is ignored.
     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(793,3): warning MT0109: The assembly 'System.Net.Http.dll' was loaded from a different path than the provided path (provided path: /Users/jfdionne/Library/Caches/Xamarin/mtbs/builds/App5.iOS/e7b3b86f111a793b6ccb2bd736c11944/bin/iPhone/Debug/System.Net.Http.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.13/lib/mono/Xamarin.iOS/System.Net.Http.dll).
     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(793,3): warning MT0129: Debugging symbol file for '/Users/jfdionne/Library/Caches/Xamarin/mtbs/builds/App5.iOS/e7b3b86f111a793b6ccb2bd736c11944/obj/iPhone/Debug/mtouch-cache/1-Link/ISocketLite.PCL.dll' does not match the assembly and is ignored.
     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(793,3): error MT2001: Could not link assemblies. Reason: Error while processing references of 'App5.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'


I'm using Forms with net standard.

**Comment by 1iveowl** [comment]
Could you try and see if you get the same issue on a different PC? Or try and clear your NuGet cache?

**Comment by JFDionne** [comment]
I just try on another computer, started a new projet, without nothing on it.
I add the package from nuget.
put 2 line of code on mainpage:
                var m_objTCP_Client = new TcpSocketClient();
                 await m_objTCP_Client.ConnectAsync("2.2.2.2", "9991");


try to build, and got the same error.

**Comment by 1iveowl** [comment]
I've tried to recreate the issue doing what you just describe, but I'm not seeing the errors.

If you take a look at the developer branch you'll see a test for both an iOS app and a Xamarin.Forms app. Both are able to link.

**Comment by JFDionne** [comment]
it's strange. 
Thank you for have checked
